---
title: "Resume"
author: "Elijah Bainbridge"
date: "9/26/2018"
output: html_document
---

Elijah Bainbridge 

120 Faculty Street, Boone, NC 28607 • Bainbridgee@appstate.edu

EDUCATION
APPALACHIAN STATE UNIVERSITY, Boone, NC	(Graduating December 2018)
Bachelors in Economics with a concentration in Environmental Economics
●	Cumulative GPA: 3.40

PROFESSIONAL EXPERIENCE
Randy’s Pizza Durham, NC                                                                          (May 2015-Auguest 2017)

Driver	

●	Ensure customer satisfaction both in-person and by phone, responsible for coordinating delivery drivers, delivering, stocking and handling new food orders

●	Communicate with coworkers and management regularly in order to collaborate and assist each other as needed

Applebee’s Boone, NC        							(June 2018-present)

Server


VOLUNTEER AND LEADERSHIP ACTIVITIES

Durham Rescue Mission, Durham, NC

Thrift Store worker	
					 
●	Processed donations

●	Worked in store with staff to stock and check-out customers 

Farm Cafe, Boone, NC

Server		
				 
●	Helped serve food to customers


COMMUNITY INVOLVEMENT 
Chess Club, Boone, NC	                                                     (August 2017-Present)
Industrial-Organizational Psychology Club, Boone, NC	(June 2016-October 2016)
National Association of Business Economics, Boone, NC	(September 2018-present)
National Association of Business Economics, Boone, NC	(September 2018-present)
Omicron Delta Epsilon, International honor society in economics, Kappa Chapter, Boone, NC  (April, 2018-Present)


ACHIEVEMENTS AND AWARDS

Appalachian State University Dean’s List                (Fall 2015, Spring 2015, Fall 2016, Spring 2016)
